export { default as msUSEnglish } from './content/ms-US-English'
export { default as spanish } from './content/spanish'
export { default as polish } from './content/polish'
export { default as portuguese } from './content/portuguese'
export { default as german } from './content/german'
export { default as french } from './content/french'
